version: '2.2'

services:
    vpn:
        image: kylemanna/openvpn
        volumes: 
            - ./conf:/etc/openvpn:rw
        ports:
            - "11194:1194"
        cap_add:
            - NET_ADMIN
        restart: unless-stopped
        
